stk.v.11.0
WrittenBy    STK_v11.4.0

BEGIN Star

    Name		 Star-70890

    BEGIN PathDescription

        Epoch		 1991.25
        RefFrame		 ICRF
        RightAscension		 2.1744894743861948e+02
        Declination		 -6.2681351862402309e+01
        ProperMotionRAPerYr		 -1.8305352568859234e-05
        ProperMotionDecPerYr		 3.7114427868800703e-06
        Parallax		 7.7164006390296602e-01
        RadialVelocity		 0.0000000000000000e+00

    END PathDescription

    BEGIN PhysicalData

        Magnitude		 1.1010000228881836e+01

    END PhysicalData

    BEGIN IdentityData

        Id		 70890

    END IdentityData


    BEGIN Extensions

        BEGIN ExternData
        END ExternData

        BEGIN ADFFileData
        END ADFFileData

        BEGIN AccessConstraints
            LineOfSight IncludeIntervals
        END AccessConstraints

        BEGIN Desc
            BEGIN LongText
Source:                Hipparcos 2
Catalog Id:            Hip 70890
Reference Frame:      ICRF
Epoch:                 J1991.25
Visual Magnitude:      11.01
B-V:                   1.81
Constellation:         Centaurus
            END LongText
        END Desc

        BEGIN Crdn
        END Crdn

        BEGIN Graphics

            BEGIN Attributes

                MarkerColor		 #ff0000
                LabelColor		 #ff0000
                MarkerStyle		 2
                FontStyle		 0

            END Attributes

            BEGIN Graphics

                Show		 On
                Inherit		 On
                ShowLabel		 On
                ShowMarker		 On

            END Graphics
        END Graphics

        BEGIN VO
        END VO

    END Extensions

END Star

